codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project: off
    patch: off
  precision: 2
  round: down
  range: "2...3"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
